toggleEffectsStatus = false
colorMode = "Effect"
toggleMovementStatus = false
toggleEquipmentStatus = false

[uiConfig]
toggleSimpleHUDEnhanced = true
textColor = 16777215
textBackground = true
textScale = 100
textAlignment = "Right"

[statusElements]
Xcords = 100
Ycords = 50
toggleLightLevel = false
togglePlayerName = false
togglePing = true
toggleTPS = true
toggleServerName = false
toggleServerAddress = false

[statusElements.coordinates]
toggleCoordinates = true
toggleDirection = true
toggleOffset = true
toggleNetherCoordinateConversion = false
toggleChunkCoordinates = false
toggleSubChunkCoordinates = false

[statusElements.fps]
toggleFPS = true
toggleColourFPS = true

[statusElements.playerSpeed]
togglePlayerSpeed = true
togglePlayerVerticalSpeed = true

[statusElements.Biome]
toggleBiome = false
toggleBiomeLabel = false

[statusElements.gameTime]
toggleGameTime = true
toggleGameTime24Hour = false
toggleGameDayCounter = false

[statusElements.systemTime]
toggleSystemTime = true
textScale = 100
textBackground = false
toggleSystemTime24Hour = false

[statusElements.counters]
toggleEntityCount = false
toggleParticleCount = false

[statusElements.counters.chunkCount]
toggleChunkCount = false
toggleTotal = false
toggleLoaded = false

[effectsStatus]
backgroundColor = -2147483648
beneficialForegroundColor = -2130706433
harmfulForegroundColor = -2130706433
neutralForegroundColor = -2130706433

[movementStatus]
toggleMovementStatus = false
textScale = 100
movementStatusLocationX = 0
movementStatusLocationY = 50

[movementStatus.movementTypes]
toggleSprintStatus = true
toggleSneakStatus = true
toggleFlyingStatus = true
toggleSwimmingStatus = true

[paperDoll]
togglePaperDoll = false
togglePaperDollTimer = false
paperDollTimeOut = 3000
textScale = 100
paperDollLocationX = 100
paperDollLocationY = 0

[equipmentStatus]
showCount = false
showNonTools = false
textScale = 100
equipmentOrientation = "Horizontal"
equipmentAlignment = "Auto"
equipmentStatusLocationX = 50
equipmentStatusLocationY = 88

[equipmentStatus.Durability]
showDurability = true
showTotalCount = false
showDurabilityAsPercentage = false
showColour = true
showDurabilityAsBar = true

[equipmentStatus.Durability.slots]
Head = true
Body = true
Legs = true
Boots = true
OffHand = true
MainHand = true

[equipmentStatus.slots]
Head = true
Body = true
Legs = true
Boots = true
OffHand = true
MainHand = true
